CREATE TABLE [dbo].[LoudSpeaker]
(
	[RegNo] NUMERIC NOT NULL PRIMARY KEY, 
    [PoliceStation] VARCHAR(50) NULL, 
    [FullNmae] VARCHAR(50) NULL, 
    [Mobile] NUMERIC(10) NULL, 
    [Address] VARCHAR(MAX) NULL, 
    [OrgType] VARCHAR(50) NULL, 
    [OrgName] VARCHAR(50) NULL, 
    [OrgAddress] VARCHAR(MAX) NULL, 
    [Telephone] NUMERIC(12) NULL, 
    [OfficeRegNo] VARCHAR(50) NULL, 
    [Doc] NVARCHAR(50) NULL, 
    [Name] VARCHAR(50) NULL, 
    [Contact] NUMERIC NULL, 
    [Oaddress] VARCHAR(MAX) NULL, 
    [Nature] VARCHAR(50) NULL, 
    [Venue] VARCHAR(50) NULL, 
    [AMfrom] VARCHAR(50) NULL, 
    [PMTo] VARCHAR(50) NULL, 
    [PMFrom] VARCHAR(50) NULL, 
    [PMToo] VARCHAR(50) NULL, 
    [FromDate] DATE NULL, 
    [ToData] DATE NULL, 
    [LoudspeakerNo] INT NULL, 
    [Generator] VARCHAR(50) NULL, 
    [Permission] VARCHAR(50) NULL, 
    [PerDoc] NVARCHAR(MAX) NULL, 
    [Status] VARCHAR(50) NULL
)